<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
	<title><?php echo getTitle() ?></title>
	<link rel="stylesheet" type="text/css" href="theme/css/bootstrap.min.css"/>
	<link rel="stylesheet" type="text/css" href="theme/css/bootstrap.css"/>
	<link rel="stylesheet" type="text/css" href="theme/css/jquery-ui.min.css"/>
	<link rel="stylesheet" type="text/css" href="theme/css/jquery.selectBoxIt.css"/>
	<link rel="stylesheet" type="text/css" href="theme/css/font-awesome.min.css"/>
	<link rel="stylesheet" type="text/css" href="theme/css/backend.css"/>
</head>
<body>
